import type { Config } from 'tailwindcss'

const config: Config = {
	darkMode: ['selector', '[data-mode="dark"]'],
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	theme: {
		screens: {
			'2xs': '370px',
			'xs': '480px',
			'sm': '640px',
			'md': '768px',
			'lg': '1024px',
			'xl': '1280px',
			'2xl': '1536px',
		},
		extend: {
			colors: {
				'mode-50': 'rgba(var(--mode-50))',
				'mode-100': 'rgba(var(--mode-100))',
				'mode-150': 'rgba(var(--mode-150))',
				'mode-200': 'rgba(var(--mode-200))',
				'mode-250': 'rgba(var(--mode-250))',
				'mode-300': 'rgba(var(--mode-300))',
				'mode-350': 'rgba(var(--mode-350))',
				'mode-400': 'rgba(var(--mode-400))',
				'mode-450': 'rgba(var(--mode-450))',
				'mode-500': 'rgba(var(--mode-500))',
				'mode-550': 'rgba(var(--mode-550))',
				'mode-600': 'rgba(var(--mode-600))',
				'mode-650': 'rgba(var(--mode-650))',
				'mode-700': 'rgba(var(--mode-700))',
				'mode-750': 'rgba(var(--mode-750))',
				'mode-800': 'rgba(var(--mode-800))',
				'mode-850': 'rgba(var(--mode-850))',
				'mode-900': 'rgba(var(--mode-900))',
				'mode-950': 'rgba(var(--mode-950))',
				'mode': 'rgba(var(--mode))',
				'mode-foreground': 'rgba(var(--mode-foreground))',
				'mode-contrast': 'rgba(var(--mode-contrast))',
				'mode-contrast-foreground': 'rgba(var(--mode-contrast-foreground))',
				'mode-accent': 'rgba(var(--mode-accent))',
				'mode-accent-foreground': 'rgba(var(--mode-accent-foreground))',
				'mode-contrast-accent': 'rgba(var(--mode-contrast-accent))',
				'mode-contrast-accent-foreground': 'rgba(var(--mode-contrast-accent-foreground))',
				'primary': 'rgba(var(--primary))',
				'primary-foreground': 'rgba(var(--primary-foreground))',
				'secondary': 'rgba(var(--secondary))',
				'secondary-foreground': 'rgba(var(--secondary-foreground))',
				'destructive': 'rgba(var(--destructive))',
				'destructive-foreground': 'rgba(var(--destructive-foreground))',
				'success': 'rgba(var(--success))',
				'success-foreground': 'rgba(var(--success-foreground))',
				'warning': 'rgba(var(--warning))',
				'warning-foreground': 'rgba(var(--warning-foreground))',
				'info': 'rgba(var(--info))',
				'info-foreground': 'rgba(var(--info-foreground))',
				'help': 'rgba(var(--help))',
				'help-foreground': 'rgba(var(--help-foreground))',
				'brand': 'rgba(var(--brand))',
				'brand-foreground': 'rgba(var(--brand-foreground))',
				'muted': 'rgba(var(--muted))',
				'muted-foreground': 'rgba(var(--muted-foreground))',
				'background': 'rgba(var(--background))',
				'foreground': 'rgba(var(--foreground))',
				'ring-color': 'rgba(var(--ring-color))',
			},
			keyframes: {
				'slide': {
					'0%': {
						transform: 'translateX(-100%)',
					},
					'100%': {
						transform: 'translateX(100%)',
					},
				},
			},
		},
	},
}

export default config
