const SCROLLABLE_Y_OFFSET = 75
const SCROLLABLE_X_OFFSET = 300

const SCROLLABLE_TRACK_DATASET = "data-scrollable-track"

export { SCROLLABLE_TRACK_DATASET, SCROLLABLE_Y_OFFSET, SCROLLABLE_X_OFFSET }
