const DOCUMENT_MODE_ATTRIBUTE_KEY = 'data-mode'

const DOCUMENT_MODE_LOCAL_STORAGE_KEY = '_document_mode'

const DEFAULT_DOCUMENT_MODE = 'light'

export { DOCUMENT_MODE_ATTRIBUTE_KEY, DOCUMENT_MODE_LOCAL_STORAGE_KEY, DEFAULT_DOCUMENT_MODE }
